### ISSUE TITLE
Disable New User Registrations

### ISSUE THREAD

**Issue by CorneliousJD** [hay-kot/homebox#111]
### What is the problem you are trying to solve with this feature?

I'd like to set this up via reverse proxy so it's accessible from outside my home, at homebox.domain.com 
The problem is, if someone else stumbles across this, they could simply register a new account.

### What is the solution you are proposing?

Having a env variable for the docker container such as REGISTRATIONS=false (likely should be set by default) this way it will allow ONE user (admin) to register, and then auto-lock registrations once there's an admin user.

### What alternatives have you considered?

Not putting it behind reverse proxy, but then I would need to rely on VPN to access this data outside the home.

### Additional context

It's possible to have this as a setting in the admin panel once that's finished, instead of a variable.
I assume adding a variable to disallow new user registrations would be faster to implement though, and is the way I see lots of other containers work.

Thank you for the consideration!

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by CorneliousJD** [comment]
Sorry, I'm dumb and only searched for open/closed issues.
I see the variable already exists in the docs.

**HBOX_ALLOW_REGISTRATION** is what I was looking for!

**Comment by jpbaril** [comment]
@hay-kot Sorry to bring back this issue, but I have set this variable but registration is still available.
I have set it this way in docker-compose.yml
```
    environment:
     - HBOX_OPTIONS_ALLOW_REGISTRATION=false
```
I can then defintely see it in the container when doing 'printenv' command:
```
/app # printenv
HOSTNAME=ca6fb5bcd843
HBOX_STORAGE_DATA=/data/
SHLVL=1
HOME=/root
HBOX_MODE=production
HBOX_OPTIONS_ALLOW_REGISTRATION=false
TERM=xterm
HBOX_STORAGE_SQLITE_URL=/data/homebox.db?_fk=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app
```
What's wrong ?

**Comment by rursache** [comment]
same issue here as @jpbaril 

i'm using docker run and i tried all the possible syntax yet the registration is still open:
```
  -e HBOX_OPTIONS_ALLOW_REGISTRATION=FALSE \
  -e HBOX_OPTIONS_ALLOW_REGISTRATION=False \
  -e HBOX_OPTIONS_ALLOW_REGISTRATION=false \
```

my full docker run command:
```
docker run -d \
  --name homebox \
  --restart unless-stopped \
  -p 3100:7745 \
  -e TZ=Europe/Bucharest \
  -e HBOX_WEB_MAX_UPLOAD_SIZE=100 \
  -e HBOX_OPTIONS_ALLOW_REGISTRATION=false \
  -v /home/radu/.homebox:/data \
  ghcr.io/hay-kot/homebox:latest
```

@hay-kot can you take a look please?

**Comment by CorneliousJD** [comment]
I can confirm that I'm now seeing registrations open again - perhaps a regression?

Howe can I delete a user who's registered (I made a test one just now) and want to purge them.

**Comment by hay-kot** [comment]
@CorneliousJD, you'd have to login with the newly created user and delete their account. However, I don't believe any user was created. It looks like we have a null reference panic that is causing an unexpected error and the UI just says a user is created when one is not. 

Can either of you report back on if you can login with your newly "registered" user?

**Comment by hay-kot** [comment]
Should be fixed with https://github.com/hay-kot/homebox/pull/282/commits/25ef2d0f5140b39a69d2f0ee8bcce529d9437831

**Comment by rursache** [comment]
@hay-kot thanks for your effort! I think the "sign up" button should be also hidden if registrations are closed?

**Comment by kmanwar89** [comment]
I'm confirming that I'm still facing this issue even after passing the environment variable for `HBOX_OPTION_ALLOW_REGISTRATION=false`.  Is this the expected behavior?

The login screen shows: Version: v0.8.0 ~ Build: 44f13f751ab8d33ee66485c0b3d9c658e86c3a36

**Comment by hay-kot** [comment]
@rursache - that wasn't apart of the original work, it was purely an API router guard. I can see about adding something to the API so we can hide the registration if it's disabled. 

@kmanwar89 - You will still see this issue until I release v0.8.1 - probably tomorrow or Thursday.

**Comment by hay-kot** [comment]
Fixed in [v0.8.1](https://github.com/hay-kot/homebox/releases/tag/v0.8.1) with the "Register" button now hidden when disabled. 🎉

**Comment by kmanwar89** [comment]
Thanks @hay-kot.  I'm unfortunately still not seeing the register button disabled, even with the environmental variables passed as I mentioned in my last comment. I see the register box is now a black solid box that, when you hover over it, it shows the word "register", but it doesn't seem to actually *disable* it.  I can confirm I'm on `Version: v0.8.1 ~ Build: efd7069fe4d39284deb3ded3db1726b9d8ddb5f9`, having just upgraded.

I tore down my container (deleted it, along with the image) and brought it back up.  The compose file the entire time contains the disable registration variable, but I'm still able to register with 0 issues.

Any ideas?

**Comment by hay-kot** [comment]
> HBOX_OPTION_ALLOW_REGISTRATION=false

Should be 

`HBOX_OPTIONS_ALLOW_REGISTRATION=false`

I'm not sure what I did with the button styles, but I'll fix that shortly...
