### ISSUE TITLE
Date isn't displayed correctly on web view

### ISSUE THREAD

**Issue by Dxvxdffm** [hay-kot/homebox#236]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

nightly

### What is the issue you are experiencing?

I just checked out the nightly version and saw that there is still this date issue. When I save an item as purchased on the 15th jan 2023, it saves it as 14th jan 2023, it always go on day back and saves that then, same for sold and warranty dates.

### How can the maintainer reproduce the issue?

Edit an item, use any of the date fields and save it for a custom date.
Save the item and it shows a day before the saved date.

### Deployment

Docker (Synology)

### Deployment Details

Issue exists on my Docker but on the demo website as well.

**Comment by Dxvxdffm** [comment]
Just noticed it saves one day before the current date every single time you save the item, even if you didn't changed something at the date fields.

**Comment by hay-kot** [comment]
@Dxvxdffm, I can't replicate it locally. What time zone are you in? Guessing this is a problem with conversion from frontend -> backend datetimes...

**Comment by Dxvxdffm** [comment]
I live in Europe/Berlin (GMT+1).

**Comment by Zackyist** [comment]
Same problem here. For me choosing the date from the picker for purchase date it shows correctly (albeit in an American format) but when I save it, it shows a value 2 days before the date. When I chose a warranty date at the same time, it saved the purchase date as 2 days before the set date and the warranty date as 1 day before its date. In addition a bogus purchase, warranty and sold date was added to every other item I had created - it was set to the last date of the warranty year (12/31/2024 in this case).

The server running the Docker container has a timezone of Etc/UTC. The computer and browser I am using Homebox from use Europe/Helsinki.

**Comment by hay-kot** [comment]
Could one of you look in your browser console and see what date is being returned from the backend API?

You should be able to find the request under the network tab.

**Comment by hay-kot** [comment]
@Dxvxdffm reached out on discord and provided some additional details that I needed. It looks like the issue is indeed with the parsing of the datetime on the backend (probably relating to timezones) I'm going to work on a test case for this and will update the issue once I can replicate the problem.

**Comment by rb-26** [comment]
My date goes haywire when entering it manually. I enter "16/04/2019" as an example, and it changes it to "in 5 years (01-01-2028)"

**Comment by hay-kot** [comment]
I believe I've fixed this with the changes in #251, if any one can try to confirm if this has been fixed on the nightly image or the demo site after it's been build (about a half hour) that would be excellent!

**Comment by Dxvxdffm** [comment]
I just tested it on your demo site. Seems like its fixed, works well for me 👍

**Comment by Dxvxdffm** [comment]
Okay actually there is still a little error related to the date. It works very well now when I save it. Also after reloading the page, the date is still correct.
But as soon as I click on "Edit", the date jumps again back on one day before the set date.
As an example, I save an item as 01/29/2023, it does save it correctly. Once I click on "edit" the date jumps to 01/28/2023.
Other than that, I didn't found any other bug related to the date yet.

**Comment by hay-kot** [comment]
@Dxvxdffm - Was able to confirm the issue an I believe I fixed it in #252, could you give that a try and report back?

**Comment by Dxvxdffm** [comment]
I tried it out as well and this issue persists for all items created before today. I still have this bug on items created yesterday and older, but when I create a new item today, everything works fine. I tested it on your demo page + on my own instance with the latest nightly image.

**Comment by hay-kot** [comment]
> I still have this bug on items created yesterday and older

What happens if you edit the date on that item and save it again? Does the issue with that item go away?

**Comment by Dxvxdffm** [comment]
It seems to work on your demo instance. I will try to install the latest nightly update on my instance as well this evening and keep you updated.
One little addition:
The calendar icon is not easy to find when its white on a bright background:
![image](https://user-images.githubusercontent.com/70025707/216914723-e503f43d-e20a-4067-bd32-6ff5c7552336.png)

**Comment by hay-kot** [comment]
- https://github.com/hay-kot/homebox/pull/268

Should allow you to run that action and cleanup any remaining dates that are broken. As for the icon, I did some looking and it looks like a browser issue. They offer very little for API's to style those icons, not sure there's much I can do other than roll my own date component which puts us right back to where we were :(

**Comment by Dxvxdffm** [comment]
Thanks @hay-kot, this fixed the issue for me now 👍
And weirdly enough, the icon of the calendar now shows the black color on a white background in your latest version for me as well 😄

**Comment by Dreytac** [comment]
> Okay actually there is still a little error related to the date. It works very well now when I save it. Also after reloading the page, the date is still correct. But as soon as I click on "Edit", the date jumps again back on one day before the set date. As an example, I save an item as 01/29/2023, it does save it correctly. Once I click on "edit" the date jumps to 01/28/2023. Other than that, I didn't found any other bug related to the date yet.

I am having this exact issue on a brand new installation of v0.8.1. In AEST timezone. The date returned in the API is correct but is displayed 1 day earlier on the page. I have tried the "Zero Item Date Times" tool which didn't work (although I didn't think it would seeing as this is a brand new installation).

**Comment by Dxvxdffm** [comment]
Yeah @Dreytac, I also noticed that the issue came back again with the latest update but forgot to mention it here 😅. @hay-kot

**Comment by hay-kot** [comment]
:(

Have you thought about moving to a supported timezone?

Will look at this again today and try writing a test to accurately capture timezones. I hate Javascript 💔

**Comment by Dreytac** [comment]
> Have you thought about moving to a supported timezone?

In today's economy? I'm lucky to be able to afford rent! 😄

I do share your hatred for Javascript though.

**Comment by Dxvxdffm** [comment]
Any update here?
And btw, I know the new Maintenance feature is quite new but the date issue also happens there.

What I set up:
![image](https://user-images.githubusercontent.com/70025707/221500227-35190658-1183-4e30-b609-e51d66664dcd.png)

My current date and time
![image](https://user-images.githubusercontent.com/70025707/221500282-37001ba5-835f-4783-b828-a19fde3eb8f6.png)

But it shows up under completed and not scheduled
![image](https://user-images.githubusercontent.com/70025707/221500341-03f6ee98-066a-4950-81f4-dd3f8ea06060.png)

**Comment by jpbaril** [comment]
@hay-kot this issue does not seem to be resolved completely.
I have the opposite issue than OP. After I enter a purchase date and save, the date shown is the next day.
I'm using 0.9.1

**Comment by jpbaril** [comment]
@hay-kot this issue does not seem to be resolved completely.
I have the opposite issue than OP. After I enter a purchase date and save, the date shown is the next day.
I'm using 0.9.1

**Comment by dima-ser** [comment]
I'm also having the same issue as @jpbaril  where after I save the date, it shows the date that is one day later.

**Comment by Dreytac** [comment]
I haven't used Homebox for most of this year. I installed a completely fresh copy tonight using `v0.9.2` and the bug still exists.

Created a new item, saved it, reloaded the page and the date is displayed 1 day prior. The API is still returning the correct day.
